# Generated by Django 2.2.10 on 2020-06-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
