# Generated by Django 2.2.10 on 2020-06-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200609_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('title', 'slug')},
        ),
    ]
