# Generated by Django 2.2 on 2020-06-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200618_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebanner',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='homesidebanner',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='shopbottombanner',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='shoptopbanner',
            old_name='url',
            new_name='link',
        ),
    ]
