# Generated by Django 2.2 on 2020-06-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
