# Generated by Django 2.2 on 2020-06-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200620_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref',
            new_name='reference',
        ),
    ]
