# Generated by Django 2.2 on 2020-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
